### ISSUE TITLE
publish module with standalone bundle

### ISSUE THREAD

**Issue by falafeljan** [recogito/recogito-js#1]
when using `recogito-js` via npm, developers will have to provide all the build/webpack tooling by themselves when loading the annotation editor via `import {init} from '@recogito/recogito-js`. this entails modules like `node-sass`—yet the developers' tooling might be entirely different.

i propose to use the `prepare` or `prepublishOnly` npm scripts (https://docs.npmjs.com/misc/scripts#prepublish-and-prepare) in order to ensure that each published version of this library contains the standalone build as well. subsequently, developers could load it via e.g. `import {init} from '@recogito/recogito-js/dist/recogito.js` while being independent in their own technology stack (being it react, vue, svelte, sass, css-in-js, etc.).

the same could be applied to the client core library (https://github.com/recogito/recogito-client-core). some [best practices](https://blog.logrocket.com/the-complete-guide-to-publishing-a-react-package-to-npm/) on publishing react components recommend on pointing the `main` field of the `package.json` manifest to the standalone build and against publishing the sources at all.

alternatively, one can currently use the build files from each github release, but this entails managing bundles directly without npm...

**Comment by rsimon** [comment]
Honestly: I have __no__ idea how that works :-) But I was wondering myself whether it's possible to get rid of the need to have all the dev dependencies for `recogito-client-core` while working on `recogito-js`. I'll dig into the links you posted - thanks! But if you get a chance for a pull request & some documentation, that would be awesome of course!

**Comment by falafeljan** [comment]
> Honestly: I have no idea how that works :-)

no worries, it is indeed very confusing—and publishing components becomes even more complex when react modules bring their own styling, as the sheer amount of solutions for styling react components even divides the react community.

i'm writing more prose than code at the moment, but i'd be glad to propose some solution on this soon!

**Comment by rsimon** [comment]
Cool, never mind if it takes a while. For now, I'm happy enough to have this published via NPM to begin with - and grateful for a pointer to address that problem with the dev dependencies. (My weekends and evenings tend to leave more time for reading and open sourcing lately, anyway, so I'll hopefully get around to looking into this soon-ish myself.)

**Comment by rsimon** [comment]
Ok, if I understand correctly, the ˋprepareˋ script will make sure I don‘t forget to build before publishing. But it‘s setting ˋmainˋ to the compiled index.js in ˋdistˋ that really does the trick, right?

**Comment by falafeljan** [comment]
> Ok, if I understand correctly, the prepare script will make sure I don‘t forget to build before publishing.

essentially, yes! the difference between `prepare` and `prepublishOnly` is, as far as i'm concerned, that `prepare` is also runs during `npm install` on machines that pull the module from npm. if we simply want to ensure the latest build is available, `prepublishOnly` should be sufficient!

the question on what to set `main` to is a good one. i've encountered a couple of libraries that provide both their sources (ES6/7 javascript with JSX features) as well as their bundles in the same module. this allows developers to either choose specific modules or load the whole standalone library:

```js
import {Highlighter} from '@recogito/recogito-js' // or ...
import Highlighter from '@recogito/recogito-js/highlighter' // vs. ...
import Recogito from '@recogito/recogito-js/dist/recogito.js'
```

the benefit of the former is that elaborate bundlers (webpack, rollup, etc.) could perform [tree shaking](https://webpack.js.org/guides/tree-shaking/) and thus further reduce the amount of imported code. this way, this module could serve even both the react sources as well as the bundle.

_however_ as this module intends to provide a simple, flat API for using the annotator directly on the vanilla DOM and not expose any react modules directly, IMO it would be perfectly fine to point `main` to the bundle...

**Comment by rsimon** [comment]
Ok, more for me to think & learn :-) I think publishing __just__ the distribution is perhaps the way to go for `recogito-js`. It's meant to be the default, out-of-the box thing. 

All the components that anyone would want to import individually are in `recogito-client-core`. So that's probably the one where we would want to follow the more complex bundling approach, so that tree shaking will work. I'll try to make & test that change for `recogito-js` soon-ish, and we can take it further from there.

**Comment by rsimon** [comment]
I tried pointing `main` to the minified distribution, and this seems to work (yay!) I just encountered a weird issue when importing RecogitoJS into another project:

At first, I tried to import with
```javascript
import Recogito from '@recogito/recogito-js';
```

This failed (Recogito = undefined). But things worked when I changed to 

```javascript
const Recogito = require('@recogito/recogito-js');
```

I figured it had to do with my export, so I changed it.

```javascript

// Before
// export const init = config => new Recogito(config);

// Now instead
export default {
  init: config => new Recogito(config)
}
```

However, now the `require` approach doesn't work. If you have any thoughts on what the best pattern for exporting is, let me know. (Especially in case there's a way to make both `require` and `import` work.

**Comment by falafeljan** [comment]
i didn't expect this incompatibility (more on this here: https://medium.com/@dlmanning/interoperability-between-es-modules-and-common-js-is-a-mistake-fb9ac71d96fd). while CommonJS exports an object, ES6 exports treat the `default` export differently.

the following should work with the prior approach:
```js
// named import
const { init } = require('...') // or ...
import { init } from '...'
const r = init(config)

// complete import
const Recogito = require('...') // or ...
import * as Recogito from '...'
const r = Recogito.init(config)
```

as `init` is somewhat redundant anyway, how about this (in regard to semantic versioning, this would likely break the current API though):

```js
// in the library
export class Recogito { ... }

// when using it
const { Recogito } = require('...') // or ...
import { Recogito } from '...'
const r = new Recogito(config)
```

**Comment by rsimon** [comment]
Yikes... yes agreed on both counts - let’s go for the named export, and get rid of init. I‘ll push this change to master later.

**Comment by rsimon** [comment]
Done. Also applied the same change to [Annotorious](https://github.com/recogito/annotorious): https://github.com/recogito/annotorious/commit/d4c0b8dd32b0e2a681dfd9716c91b3f3b36463d3

**Comment by rsimon** [comment]
I noticed a small problem with this. Concerning the import of the bundle into a Web page with a `<script>` tag. Since Webpack exports a "module" object is this case, the `new Recogito(config)` pattern doesn‘t work.

I therefore kept __both__ named exports, `Recogito` and `init`. That‘s obviously redundant, but allows proper looking import & init for all modes. (Otherwise, we’d need to do something like `new Recogito.Recogito(config)` in HTML Imports.

**Comment by falafeljan** [comment]
yes, i like that solution. it's backwards-compatible, too :)
