### ISSUE TITLE
loadAnnotations (question)

### ISSUE THREAD

**Issue by dtakeshta** [recogito/recogito-js#109]
I'm having an issue and it may just be related to how we are using this library.  I wanted to create the issue just to see if there is something we are missing in the documentation that would help, or perhaps just be told there is nothing we can do because of our use case. 

In our application, users have access to a wysiwyg to edit text.  We use recogito-js outside of the wysiwyg to allow users to collaborate on the text. 

Here is our issue:

If a user writes a paragraph and saves it.  Another user can create an annotation, let's just say it's the first word of the paragraph they highlight.

Then another user adds a new paragraph above this paragraph that was annotated.  

When `loadAnnotations` is called, the text that was actually highlighted is no longer highlighted, yet the text above the paragraph that was originally highlighted is now highlighted and has the span.  

When looking at the source code, it seems it's loading annotations based on position.  Which would explain why the annotations are moving around when they are loaded.

If you look at the HTML in the database, the text that was originally highlighted has the span and `r6o-annotation` class along with the `data-id`.

Was the intention of the library to handle static text?  Meaning the content isn't changing which doesn't cause `loadAnnotations` to shift around spans when it's loaded?

Hopefully that makes sense.  Just trying to figure out if there is anything that we can do to prevent this.

**Comment by rsimon** [comment]
That's right. Annotations are stored by character offset. If the text changes, you'd need to find your own way of correcting the start-/end-offsets for each annotation that's located after the change. 

I've been discussing ways of re-aligning existing annotations with modified texts at various occasions, with various partners. But there's really no good/simple solution. At least not as long as you keep the annotations separate from the text, as offset markup (which is the fundamental goal of RecogitoJS).

If your use case is rich text editing, you might be able to leverage existing annotation features built into the RTE library perhaps? Some of them have a structured model for their text that includes features like ranges and inline annotation markers, AFAIK.

**Comment by dtakeshta** [comment]
@rsimon thank you for confirming my suspicion. 

This might be a stupid question, but why couldn't the annotations just be loaded by the `data-id` and  that is added to the markup when the annotation is created rather than offset?  

Could you help point me to what is happening with `loadAnnotations`?  That way we can implement this in our application.

**Comment by rsimon** [comment]
Hm, I guess this _might_ be possible somehow. But it's simply not the way RecogitoJS works. From what you're saying, I guess you are storing the modified HTML markup in your DB. That makes sense if you see things from the perspective of rich text editing. But for RecogitoJS, the use case is completely different: people have static text/HTML, and then want to store *just* the annotations, as standoff markup, separate from the text.

No-one who's using RecogitoJS would store the whole text again after it was annotated. With RecogitoJS, you'd usually just have a simple DB, one row per annotation, and (at a minimum) a column for the annotation ID, the document ID, and the JSON annotation.

Based on the JSON, the SPANs are inserted  into the text dynamically. The SPANs wouldn't normally exist in the text beforehand! Not sure if I'm explaining this in a good way. But, essentially, RecogitoJS has almost exactly the inverse of a rich text editing model. With RTE, the whole text + markup is considered the data model. In RecogitoJS, the text is considered completely static, and the annotations are a layer that gets applied on top.

**Comment by dtakeshta** [comment]
@rsimon really appreciate the help and insight.  Yep, we are totally using the library in an unorthodox way.  We are doing exactly what you are saying.  

Can you help me understand or at least where to look (I've tried) what happens when the annotations are loaded?  I'm trying to figure out what makes the element clickable when they are loaded and the popup shows the text from the annotation.  That's the part I need to implement but can't seem to find it.  I've searched in Recogito-JS and the Client Core.

**Comment by rsimon** [comment]
The Highlighter class handles the dynamic insertion of the spans into the base markup. It also attaches the annotation object to the span itself. (Somewhat hack.)

Then the SelectionHandler is in charge of handling mouse selection - both creating new annotation ranges as well as selecting existing ones.

- https://github.com/recogito/recogito-js/blob/main/src/highlighter/Highlighter.js#L12
- https://github.com/recogito/recogito-js/blob/main/src/selection/SelectionHandler.js#L58

**Comment by rsimon** [comment]
The popup editor is indeed in the client-core package:
https://github.com/recogito/recogito-client-core/blob/main/src/editor/Editor.jsx

But that's all a bit of a legacy mess. (Which is also why we're working on a successor project. But that will work on the same principles & data model.)

**Comment by dtakeshta** [comment]
@rsimon really appreciate your help!  We will just write our own way to load annotations which should work for our odd use case.
