### ISSUE TITLE
Extending the comment popup

### ISSUE THREAD

**Issue by srinisubramanian** [recogito/recogito-js#15]
First of all thanks for a great annotation tool that just works.  I need to make a couple of enhancements and would like to get your thoughts on how to go about it so that updates to recogito-js would still not be affected due to the extensions.

1.  I need to have an at mention capability in the comments dialog.  Just like the GitHub issue @rsimon kind of mention capability
2. Also, although setAuthInfo() is used its not restricting edit/delete of another user's comments by current user.  How do we achieve that?

Any ideas on what would be the best approach to implement the above?

**Comment by rsimon** [comment]
Thanks for the positive feedback - I really appreciate that!

Re 1.: for now, I'd suggest starting with the [original code for the built-in comment widget](https://github.com/recogito/recogito-client-core/tree/main/src/editor/widgets/comment). The current comment widget is just a text area. You'd probably need to replace that with some existing component/library that has the necessary text markup capability, or build something yourself.

It's possible to plug in your own widgets, replacing the original comment widget. Therefore, you wouldn't even need to mess with the rest of the codebase, and could keep using it with future updates. I admit all of this is a bit (...) underdocumented. But a basic intro on editor plugins is here:

https://recogito.github.io/guides/extending-the-editor/

(The guide is for Annotorious. But works for RecogitoJS in exactly the same way.)

Re 2. `.setAuthInfo()` doesn't do that by default, that's right. But the functionality is built in. You need to do the following:

```js
var r = Recogito.init({
  content: 'content',
  widgets: [
    { widget: 'COMMENT', editable: 'MINE_ONLY' }
  ]
});
```

This was [introduced a while back](https://github.com/recogito/recogito-js/releases/tag/v0.2.0), but then not properly document... yet... again ;-)

Hope this helps. Do let me know if/how you get on with the mention feature. I'd be interested in this myself!

**Comment by srinisubramanian** [comment]
The editor plugin concept is very interesting. Will check if we can work with that. 

At a high level was planning to add similar to setAuthInfo to add Collaborators to the comments  Then the editor could be extended to handle the @ mention using the array of collaborators configured. Or some variation of that. Once I look at the editor plugin will work on it. Probably make a PR if design is found ok.

**Comment by rsimon** [comment]
Sounds great! Yes, I guess you could either pull the list of collaborators from the current annotations (but then potentially missing users in the system that haven't contributed yet, of course). Or load it into an in-memory array.

BTW: if you do the following:

```js
var MentionAwareCommmentWidget = function(args) {
  // ...
};

var r = Recogito.init({
  content: 'content',
  widgets: [
    { widget: MentionAwareCommentWidget, collaborators: [ 'Alice', 'Bob' ] }
  ]
});
```

Then RecogitoJS will pipe the `collaborators` arg through to the `args` that the widget is called with. (Plus: the widget can also be a React component, just in case this is relevant to you.)

**Comment by srinisubramanian** [comment]
Thanks @rsimon that's really helpful. Will do this in a branch when we l get started. Need this soon so will prioritise quickly. Thanks.

**Comment by srinisubramanian** [comment]
Wondering if it's a  better idea to use something like https://github.com/signavio/react-mentions and integrate

**Comment by srinisubramanian** [comment]
@rsimon my colleage has extended the component by forking this and the core. Before we submit it as a PR do you mind taking a look at the fork and letting us know if it's good or changes needed?

**Comment by rsimon** [comment]
@srinisubramanian awesome - yes, please do forward me the link to the fork. 

That being said: I'd (probably) prefer this to be a plugin, rather than an extension to the core codebase. But can definitely help with wrapping your fork as a plugin.

**Comment by srinidhirao** [comment]
Hi, 

This is the my fork of the recogito-client-core
https://github.com/srinidhirao/recogito-client-core

I also had to fork recogito-js repo to propagate the input (userSuggestions) to the new component:
https://github.com/srinidhirao/recogito-js

recogito-js depends on the forked recogito-client-core. You should be able to link these two with `npm link`

If you open the sample example for the comment widget if you try to type an @, then the suggestions list should popup allowing you to select a value.

**Comment by rsimon** [comment]
Hi @srinidhirao,

I tried it out - it's awesome! BTW: there's no need to change RecogitoJS, and no need to pipe `userSuggestions` through to your component manually. The framework automatically makes sure that any property you put into the init code will be forwarded as a prop. That means, in your case, if you init like this...

```js
var r = Recogito.init({
   content: 'content',
   widgets: [
     { widget: 'COMMENT', userSuggestions: users }
   ]
});
``` 

...then your component `ComponentWithAtMention` will automatically receive the users array as `props.userSuggestions`. No need to forward it manually.

You can remove this:
https://github.com/srinidhirao/recogito-js/blob/main/src/TextAnnotator.jsx#L275

(FYI: the automatic plumbing happens [here](https://github.com/recogito/recogito-client-core/blob/main/src/editor/widgets/index.js#L46-L68))

I would __love__ to wrap this as a plugin. I wonder how to be best proceed on this. Do you want to create your own permanent repository for the plugin & then I can help there with the necessary changes? Alternatively, I can also create one under the `@recogito` organization, and you could send the PR there?

The plugin, by the way, would (probably) only consist of the `ComponentWithAtMention`of the   




 makes sure that

**Comment by rsimon** [comment]
Hi @srinidhirao,

I tried it out - it's awesome! BTW: there's no need to change RecogitoJS, and no need to pipe `userSuggestions` through to your component manually. The framework automatically makes sure that any property you put into the init code will be forwarded as a prop. That means, in your case, if you init like this...

```js
var r = Recogito.init({
   content: 'content',
   widgets: [
     { widget: 'COMMENT', userSuggestions: users }
   ]
});
``` 

...then your component `ComponentWithAtMention` will automatically receive the users array as `props.userSuggestions`. No need to forward it manually.

You can remove this:
https://github.com/srinidhirao/recogito-js/blob/main/src/TextAnnotator.jsx#L275

(FYI: the automatic plumbing happens [here](https://github.com/recogito/recogito-client-core/blob/main/src/editor/widgets/index.js#L46-L68))

I would __love__ to wrap this as a plugin. I wonder how to be best proceed on this. Do you want to create your own permanent repository for the plugin & then I can help there with the necessary changes? Alternatively, I can also create one under the `@recogito` organization, and you could send the PR there?

The plugin, by the way, would (probably) only consist of the `ComponentWithAtMention` component, and a little project boilerplate around it. (An example Hello World plugin is here: https://github.com/recogito/recogito-client-plugins/tree/main/packages/widget-react-helloworld) 




 makes sure that

**Comment by srinidhirao** [comment]
Thank you. It would be great if you can create a repo under @recogito. I can make the changes and submit a PR to that.

**Comment by rsimon** [comment]
Great! I made a repository here & set up the basic project structure:
https://github.com/recogito/recogito-comments-mention

There are a few issues with the build process (dependency security warnings, and the build output is much larger than it should be) - but I'll sort this out later. 

Your modified CommentWidget should go into `index.jsx`, and your modified TextArea into `TextAreaWithMentions`.

**Comment by srinidhirao** [comment]
@rsimon I'm missing a write access on the repo. Can you please provide that so that I can push the code?

```
Pushing to https://github.com/recogito/recogito-comments-mention.git
remote: Permission to recogito/recogito-comments-mention.git denied to srinidhirao.
fatal: unable to access 'https://github.com/recogito/recogito-comments-mention.git/': The requested URL returned error: 403
```

**Comment by srinidhirao** [comment]
@rsimon I updated the plugin and added the same to the repo. But, the widget did not show up and failed with the following error:

```
WrappedWidget.jsx:29 Uncaught (in promise) TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at u.value (WrappedWidget.jsx:29)
    at P (index.js:119)
    at children.js:102
    at E (children.js:259)
    at E (children.js:254)
    at E (children.js:254) 
``` 
I compared the code with HelloWorld plugin and noticied that the webpack versions are different. I'm not sure whether that could be an issue. 
I then tried to return a very simple html in index.jsx and it also failed with the same error. This is the test code which failed ti work. 

```
import React from 'preact/compat';
import DropdownMenu from '@recogito/recogito-client-core/src/editor/widgets/comment/DropdownMenu';
import { ChevronDownIcon } from '@recogito/recogito-client-core/src/Icons';
import i18n from '@recogito/recogito-client-core/src/i18n';
import TextAreaWithMentions from './TextAreaWithMentions';

const CommentsWithMentions = props => {

    return (
        <div>
          <h1>Something</h1>
        </div>
      )

}

export default CommentsWithMentions;
```

I'm suspecting some issue in setup. I couldn't figure out  what the issue is. Thanks to the access I have pushed my plugin changes to https://github.com/recogito/recogito-comments-mention

Can you please take a look?

**Comment by rsimon** [comment]
Hi, ouch - sorry that was a bug in RecogitoJS. It supports React plugins but, apparently, did __not__ support plugins created with Preact.

I made a quick fix for this, and built a patched version of `recogito.min.js`. It's now included in the repo. I tried again with the patched version, and now the widget appears.

**Comment by rsimon** [comment]
Yikes, it looks like supporting Preact widgets will require a few more extra tweaks to the Recogito plugin API. At the moment, it only seems to work partially. I'll need to investigate how to make Preact widgets works... I'll let you know once I know more.

**Comment by srinidhirao** [comment]
ok. Thanks for the update.

**Comment by rsimon** [comment]
It looks like it's currently not possible to use Preact hooks in a Recogito plugin. Using __Hooks with React__ should work; and __class components__ should also work (both with React and Preact).

I can hopefully figure out a workaround for this in the future. But for now, this seems to be a limition :-(

**Comment by rsimon** [comment]
I refactored [Comment](https://github.com/recogito/recogito-comments-mention/blob/main/src/Comment.jsx) into a class component, and that seems to work now! However I don't get the dropdown when I type @. Everything else seems to work though.

**Comment by srinidhirao** [comment]
@rsimon I didn't see your edit so I went ahead and tried to fix this in a different way. I was able to get the input event by adding the event listener programmatically and this seems to work.
```
this.textAreaElement.current.addEventListener('input', this.onTextAreaInput.bind(this))
```

I also fixed one other issue in saving the comment. Right now it all seems to be working. I have pushed all the code to the repo. I'll also update the documentation and push an other commit.

**Comment by srinidhirao** [comment]
@rsimon I have updated the documentation as well. Please check and let me know if anything else needs to be done.

**Comment by rsimon** [comment]
@srinidhirao I checked out your lates changes and everything worked for me - it's great! Also publize this on the [Annotorious plugins page](https://recogito.github.io/annotorious/plugins/). (Editor plugins for RecogitoJS are also compatible with Annotorious, the image annotation library.)

**Comment by srinisubramanian** [comment]
@rsimon will you also be publishing this to npm?

**Comment by rsimon** [comment]
Done! https://www.npmjs.com/package/@recogito/recogito-comments-mention

**Comment by srinidhirao** [comment]
@rsimon Thanks for publishing this as a npm package. I included this npm package in my project along with recogito-js but `recogito.CommentsMention` turns out undefined. This is in an Ionic application using Angular framework. If I import the `recogito-comments-mention.min.js` file directly, it works.  I can also get the Recogito-JS to work with the npm package and without having to manually include the corresponding minified js file.

So, wondering how to get it to work with an npm package:

```typescript
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import * as Recogito from '@recogito/recogito-js';
@Component({
  selector: 'app-folder',
  templateUrl: './folder.page.html',
  styleUrls: ['./folder.page.scss'],
})
export class FolderPage implements OnInit {
  public folder: string;

  constructor(private activatedRoute: ActivatedRoute) { }

  ngOnInit() {
    this.folder = this.activatedRoute.snapshot.paramMap.get('id');

    console.log('My Content: ' + document.getElementById('myContent'))

    /**
     * |recogito.CommentsMention| returns undefined. 
     */
    // console.log(recogito.CommentsMention);

    var r = Recogito.init({
      content: document.getElementById('myContent'), // Element id or DOM node to attach to
      locale: 'auto',
      widgets: [
        /* I intend to include this plugin this way.
        { widget: Recogito.CommentsMention, userSuggestions: users }, */
        { widget: 'COMMENT' },
        { widget: 'TAG', vocabulary: ['Place', 'Person', 'Event', 'Organization', 'Animal'] }
      ],
      relationVocabulary: ['isRelated', 'isPartOf', 'isSameAs ']
    });

    // Add an event handler  
    r.on('createAnnotation', function (annotation) {
      console.log('Annotation Added: ' + JSON.stringify(annotation))
    });
  }

}

```

This is how my package.json looks like:
```json
{
  "name": "TestRecogito",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~12.0.1",
    "@angular/core": "~12.0.1",
    "@angular/forms": "~12.0.1",
    "@angular/platform-browser": "~12.0.1",
    "@angular/platform-browser-dynamic": "~12.0.1",
    "@angular/router": "~12.0.1",
    "@ionic/angular": "^5.5.2",
    "@recogito/recogito-comments-mention": "^0.1.0",
    "@recogito/recogito-js": "^1.2.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.1",
    "@angular-eslint/builder": "~12.0.0",
    "@angular-eslint/eslint-plugin": "~12.0.0",
    "@angular-eslint/eslint-plugin-template": "~12.0.0",
    "@angular-eslint/template-parser": "~12.0.0",
    "@angular/cli": "~12.0.1",
    "@angular/compiler": "~12.0.1",
    "@angular/compiler-cli": "~12.0.1",
    "@angular/language-service": "~12.0.1",
    "@ionic/angular-toolkit": "^4.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~3.7.1",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "style-loader": "^2.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.2.4"
  },
  "description": "An Ionic project"
}

```

**Comment by rsimon** [comment]
You're not importing the plugin anywhere, if I can see correctly. I haven't tried importing into an npm build yet, but I think it would have to look something like this:

```js
import CommentsMention from '@recogito/recogito-comments-mention';

// and then on init
    { widget: CommentsMention, userSuggestions: users }
```

**Comment by srinidhirao** [comment]
This module is in-fact resolving to a JSX file instead of I guess the minified JS file. 

![Screenshot 2021-06-09 at 2 22 51 PM](https://user-images.githubusercontent.com/9901457/121324348-464c0d80-c92e-11eb-97d5-255d4cbb16a1.png)

**Comment by rsimon** [comment]
Ah - good point. Yes, that's right you'll need the compiled plugin of course! 

Can you try importing from `@recogito/recogito-comments-mention/dist/recogito-comments-mention.min.js`?

That should resolve directly to the built/minified distribution.

**Comment by bharatrnair** [comment]
Hi @rsimon , @srinidhirao 
I'm using the Recogito plugin to display PDFs and add annotations. However, I need an additional feature: the ability to highlight text within the PDF using multiple colors. Is there a way to achieve this? Thanks in advance!

**Comment by rsimon** [comment]
Hi @bharatrnair, 

formatters are probably what you are looking for: https://github.com/recogito/recogito-js/wiki/API-Reference#formatters

BTW, you may also be interested in the upcoming [next version of RecogitoJS](https://github.com/recogito/text-annotator-js). It's still in alpha & there's no documentation yet. (Currently, you'd need to figure out your way by looking at the code and test examples.) But there's also a dedicated PDF annotation package: https://github.com/recogito/pdf-annotator-js

**Comment by bharatrnair** [comment]
Thanks a lot @rsimon,  for the support.  But my actual need is to select and highlight specific parts in the pdf using multiple color from where I can select the color for highlighting.

**Comment by rsimon** [comment]
Yes, you'd need to build your own controls that allow you to pick a color. Then that color choice would need to be stored in the annotation, and the formatter applies the style. See this tutorial for info:
https://observablehq.com/@rsimon/writing-annotorious-formatters-pt-1

(It's for Annotorious, but works the same way for RecogitoJS).

**Comment by bharatrnair** [comment]
Thanks @rsimon ;)

**Comment by bharatrnair** [comment]
Hi @rsimon, Is there any implementation like where I can get the comments added in the annotations  as data, so that I can use that data to display in another component.

**Comment by rsimon** [comment]
I'm afraid not. You'd simply have to listen to the lifecycle events (create, update, delete) and maintain your own state. FWIW, this is easier in the upcoming release, because that has better state management. (And a React wrapper with hooks, in case you are using React.)

> And also, I want to select and highlight specific sentence or words using multiple custom colors , annotations not needed for that, so can I achieve that using the formatters also?

You don't need to add a comment. It's perfectly find to just create an "empty" annotation, and then use formatters. (You still need to store the color information in the annotation somehow, though - see Annotorious tutorial).

**Comment by AnthonyKamers** [comment]
Hello, I'm trying to add a custom widget to RecogitoJS (using that NPM package provided) using React components, but I'm getting an error probably because of what @rsimon said here:

> It looks like it's currently not possible to use Preact hooks in a Recogito plugin. Using **Hooks with React** should work; and **class components** should also work (both with React and Preact).
> 
> I can hopefully figure out a workaround for this in the future. But for now, this seems to be a limition :-(

I tried to use class components, functional components, changing React for Preact, but nothing seemed to work.

I would like to use the recogito-js library directly or modify the minimum possible. Is there a way I can use the webpack provided in [recogito-comments-mention](https://github.com/recogito/recogito-comments-mention/blob/main/webpack.config.js) so [recogito-client-core](https://github.com/recogito/recogito-client-core/tree/main) would accept React components?

I just instantiate a new Recogito instance as the following:
![image](https://github.com/recogito/recogito-js/assets/18016948/24ca44d2-6ca5-4af7-bb9f-12dd1179802c)

While the `HelloPluginJsx` is the following:
![image](https://github.com/recogito/recogito-js/assets/18016948/06602700-bb4b-4b1b-a715-9ae98fcca490)

I get the following error:
![image](https://github.com/recogito/recogito-js/assets/18016948/c3d9001d-fc53-4126-9bf8-12a4df494dca)

Debugging it, I found out that `recogito-client-core/src/editor/widgets/index.jsx#getWidget` is not considering it as a React plugin, so  it calls `instantiate(args)` directly.

**Comment by Kontosoros** [comment]
Hi guys.. how can implement default tags when I create a new annotation? I want to have a default options when I make a new annotation

**Comment by rsimon** [comment]
You'd need to add those programmatically after the annotation was created. Listen to the `createAnnotation` event, add the bodies, and update the annotation. Specifics depend on which version of Annotorious you are using. But that's the basic approach.

**Comment by Kontosoros** [comment]
I Don not know if there is any parameter to add in line 63 in order to pass some default tags ... when I use the on.create it displays a window that does not contain any default tag... I have to write in the input placeholder the apopriate tag .. 
  private reinitializeRecogito(): void {
    const contentElement = document.getElementById('my-content');
    if (contentElement) {
      // Initialize or reinitialize recogito instance
      this.recogitoInstance = new Recogito({
        content: contentElement,
        formatter: this.formatter,
      });

      // Attach event listeners again
      this.recogitoInstance.on('deleteAnnotation', (annotation) => {
        this.fileService.deleteAnnotation(annotation);
      });

      this.recogitoInstance.on('updateAnnotation', (annotation) => {
        this.fileService.addAnnotation(annotation);
      });

      this.recogitoInstance.on('createAnnotation', (annotation) => {
        this.fileService.addAnnotation(annotation);
      });
    }
  }
