### ISSUE TITLE
readOnly flag does not seem to take effect

### ISSUE THREAD

**Issue by srinisubramanian** [recogito/recogito-js#16]
The readOnly does not make any difference in this code snippet

```
Recogito.init({content: document.getElementById('textfield'), readOnly: true });
```

Any idea what's wrong?

**Comment by rsimon** [comment]
Ouch, sorry - this was a bug that was introduced with a recent API change. (The API was changed for [Annotorious](https://github.com/recogito/annotorious), and then RecogitoJS fell behind.) Fixed now in the main branch!
