### ISSUE TITLE
Tagged annotations cannot be deleted

### ISSUE THREAD

**Issue by pivot5** [recogito/recogito-js#18]
This issue can be reproduced by visiting the [demo](https://recogito.github.io/recogito-js/), creating a new annotation with one or more tags, and then attempting to delete the annotation. Rather than remove the whole annotation, only the comment is removed and tags are kept in an empty annotation. Alternatively, one can also attempt to delete the 'Troy' premade annotation for the same results.

**Comment by rsimon** [comment]
The annotation will remain as long as it has any content (comments or tags). To remove the annotation, you need to delete the comment __and__ each tag. Click the tag -> click the trashcan icon.

I know this isn't ideal from a usability perspective. An extra __Delete__ button to delete everything in one go is on the way.

**Comment by pivot5** [comment]
Understood, no problems if it's been noticed & there's an upcoming feature.
