### ISSUE TITLE
Annotations and contenteditable

### ISSUE THREAD

**Issue by situx** [recogito/recogito-js#24]
I annotate words in a p container which can also be made editable using the contenteditable attribute of HTML.
I experience the following behavior:
Initial situation:

Example line: 2‘. […] x GU4? 

I can add an annotation to GU4, let's say "abc".

Then I modify the line using contenteditable=true to the following:

 2‘. […] x abcde GU4? 

Until here everything is fine because the annotation is moved with GU4.

Now I add another annotation to GU4 and the position of the annotation of GU4 is reset to its original position before I edited the text field.

Is this the anticipated behavior or is this a bug?

**Comment by rsimon** [comment]
Annotations record their position in terms of character offset from the start. Unless you update all annotations with every change to the text, annotation offsets will get out of sync.

Or in other words: annotating editable content isn't currently supported.
