### ISSUE TITLE
How make `recogito-js` working with an `Electron-React-Typescript-Webpack` app ?

### ISSUE THREAD

**Issue by raphael10-collab** [recogito/recogito-js#25]
I'm trying to use `recogito-js` within my Electron-React-Typescript-Webpack app.
Since I set for security reasons 

      nodeIntegration: false,
      enableRemoteModule: false,
      contextIsolation: true,
      nodeIntegrationInWorker: false,
      nodeIntegrationInSubFrames: false,
      sandbox: true,
      webSecurity: true,
      webviewTag: false,

I cannot use `import` nor 'require` within an `HTML` page.

So, two possibilities left:
1) directly import the `<script>` tag
2) use the bundler `Webpack` in order make to "convert" the recogito-js code into something the renderer can understand.

I imported and unzipped `recogito-js-1.0.0.zip` in the subfolder of the `html` page,
but both:

    <script src="./recogito.min.js"></script>
    <script src="./recogito.min.css"></script>

and 

    <script src="recogito.min.js"></script>
    <script src="recogito.min.css"></script>

give: `Failed to load resource: net::ERR_FILE_NOT_FOUND`

What should I add / modify in my `webpack.config.js`, in order to make my Electron app recognise and use `recognito-js?.

This is my `webpack` configuration:

    const path = require('path');
    const cwd = process.cwd();
    const HtmlWebpackPlugin = require('html-webpack-plugin');
    const CopyPlugin = require("copy-webpack-plugin");
    const MiniCssExtractPlugin = require('mini-css-extract-plugin');
    const webpack = require('webpack');

    function srcPaths(src) {
      return path.join(__dirname, src);
    }

    // Creates Webpack Aliases using CWD path
    const createWebpackAliases = (als) => {
      const result = {};
      for (const name in als) {
        result[name] = path.join(cwd, als[name]);
      }
      return result;
    };

    const aliases = createWebpackAliases({
      '@src': 'src',
      '@app': 'src/app',
      '@app_A': 'src/app_A',
      '@app_trial': 'src/lib/pdfjs-dist/web',
      '@about': 'src/sections/about',
      '@account': 'src/sections/Account/account',
      '@static': 'src/static',
      '@pdfviewer': 'src/lib/pdfjs-dist/web/viewer',
    });

    const isEnvProduction = process.env.NODE_ENV === 'production';
    const isEnvDevelopment = process.env.NODE_ENV === 'development';

      // main process
    var main_config = {
         mode: isEnvProduction ? 'production' : 'development',
        entry: './src/main/main.ts',
        target: 'electron-main',
        resolve: {
          extensions: ['.jsx', '.js', 'ts'],
        },
        // https://github.com/slackapi/node-slack-sdk/issues/746#issuecomment-778804407
        externals: [
          {
            'utf-8-validate': 'commonjs utf-8-validate',
            bufferutil: 'commonjs bufferutil',
          }
        ],
        module: {
          rules: [
            {
              test: /\.ts$/,
              include: /src/,
              use: [{ loader: 'ts-loader' }]
            },
            {
              // css files
              test: /\.(sass|less|css)$/i,
              use: [
                {
                  loader: 'style-loader'
                },
                {
                  loader: 'css-loader'
                },
                {
                  loader: 'less-loader',
                },
              ],
            },
          ]
        },
        output: {
           path: __dirname + '/dist',
          filename: 'main.js'
        },
        node: {
          __dirname: false,
          __filename: false
        },
    };

      // renderer process
    var renderer_config =  {
        mode: isEnvProduction ? 'production' : 'development',
        entry: {
          app: './src/app/index.tsx',
          app_A: './src/app_A/index_A.tsx',
          app_B: './src/app_B/index_B.tsx',
          infoBasket: './src/app/sections/infobasket/Infobasket.tsx',
          style: './src/app/styles/index.css',
          style_A: './src/app_A/styles/index.css',
        },
        target: 'electron-renderer',
        resolve: {
          extensions: ['.jsx', '.js', '.tsx', '.ts'],
          alias: {
            // Custom Aliases
            ...aliases,
          },
        },
        output: {
          path: __dirname + '/dist/',
          filename: '[name].js',
        },
        // https://github.com/slackapi/node-slack-sdk/issues/746#issuecomment-778804407
        externals: [
          {
            'utf-8-validate': 'commonjs utf-8-validate',
            bufferutil: 'commonjs bufferutil',
          },
        ],
        module: {
          rules: [
            {
              test: /\.(js|ts)x?$/,
              exclude: /node_modules/,
              use: {
                loader: 'babel-loader',
              },
            },
            {
              // css files
              test: /\.css$/i,
              use: [
                {
                  loader: 'style-loader'
                },
                {
                  loader: 'css-loader'
                },
              ],
            },
            {
              // Font files
              test: /\.(woff|woff2|ttf|otf)$/,
              loader: 'file-loader',
              options: {
                name: '[hash].[ext]',
                outputPath: 'dist/assets/css/'
              }
            },
            {
              // image files
              test: /\.(jpe?g|png|gif|svg)$/i,
              loader: 'file-loader',
              options: {
                name: '/pics/[name].[ext]',
                outputPath: 'dist/assets/pics/'
              }
            }
          ],
        },
        node: {
          __dirname: false,
         __filename: false
        },
        plugins: [
          new HtmlWebpackPlugin({
            filename: 'index.html',
            template: './src/app/index.html',
            inject:'body',
            chunks: ['app'],
          }),
          new HtmlWebpackPlugin({
            filename: 'index_A.html',
            template: './src/app_A/index_A.html',
            inject: 'body',
            chunks: ['app_A']
          }),
          new HtmlWebpackPlugin({
            filename: 'viewer.html',
            template: './src/lib/pdfjs-dist/web/viewer.html',
            inject: 'body',
            chunks: ['app_viewer']
          }),
          new HtmlWebpackPlugin({
            filename: 'index_trial.html',
            template: './src/app_A/index_trial.html',
            inject: 'body',
            chunks: ['index_trial']
          }),
          new MiniCssExtractPlugin({
            filename: '[name].css',
            chunkFilename: '[id].css',
            linkType: 'text/css',
          }),
          new CopyPlugin({
            patterns: [
              {
                from: path.resolve(__dirname, "./src/lib"),
                to: path.resolve(__dirname, "./dist/lib")
              },
              {
                from: path.resolve(__dirname, "./src/assets/css"),
                to: path.resolve(__dirname, "./dist/assets/css")
              },
              {
                from: path.resolve(__dirname, "./src/assets/pics"),
                to: path.resolve(__dirname, "./dist/assets/pics")
              }
            ],
            options: {
              concurrency: 100,
            },
          }),
        ]
    }

    module.exports = [ main_config, renderer_config ];

Looking forward to your kind help.

**Comment by rsimon** [comment]
Hi, sorry I don't know enough about your tech stack (Electron, TypeScript) to be of any real help here. But aren't you building some kind of minified bundle for your application? The intention is definitely not to `import` in the HTML page. `import` would be the recommended practice for your React project before bundling. Or am I misunderstanding things completely?

**Comment by raphael10-collab** [comment]
@rsimon You are right. 
I was making an attempt, a wrong one.

using `import` in the `React App_B.tsx` : 


    import { Recogito } from '@recogito/recogito-js';

    var r = Recogito.init({
       //content: 'content', // Element id or DOM node to attach to
       //locale: 'auto'
    });

I get `Uncaught TypeError: _recogitoJs.Recogito.init is not a function` 
![image](https://user-images.githubusercontent.com/70313067/114833928-5d5bfc80-9dd0-11eb-81c1-25101761b50f.png)

I guess I have to add/modify something in `webpack.config.js`

**Comment by rsimon** [comment]
Init works in different ways, depending on whether you go via the `<script>` tag or `import`. When `import`ing, use this:

```js
import { Recogito } from '@recogito/recogito-js';

import '@recogito/recogito-js/dist/recogito.min.css';

const r = new Recogito({ content: 'my-content' });
``` 

(See also the [Readme](https://github.com/recogito/recogito-js). The reason for the differnt methods has something to do with the way module loading works in different environments I think. Frankly, I couldn't ultimately figure out how to make it behave in an identical way.)

**Comment by raphael10-collab** [comment]
Putting in the React `App_B.tsx` : 


    import { Recogito } from '@recogito/recogito-js';
    import '@recogito/recogito-js/dist/recogito.min.css';

    const r = new Recogito({ content: 'my-content' });

    function App_B() {

        return (
          <div className='outer-container'>
            <div id="content" className="plaintext">
              <h1>Homer: The Odyssey</h1>
              <p>
                <strong>Tell me, O muse,</strong> of that ingenious hero who travelled far and wide after he had sacked
                the famous town of Troy. Many cities did he visit, and many were the nations with whose manners and customs
                he was acquainted; moreover he suffered much by sea while trying to save his own life and bring his men safely
                home; but do what he might he could not save his men, for they perished through their own sheer folly in eating
                the cattle of the Sun-god Hyperion; so the god prevented them from ever reaching home. Tell me, too, about all
                these things, O daughter of Jove, from whatsoever source you may know them.
              </p>
              <p>
                <strong>So now all who escaped death in battle</strong> or by shipwreck had got safely home except Ulysses,
                and he, though he was longing to return to his wife and country, was detained by the goddess Calypso, who
                had got him into a large cave and wanted to marry him. But as years went by, there came a time when the gods
                settled that he should go back to Ithaca; even then, however, when he was among his own people, his troubles
                were not yet over; nevertheless all the gods had now begun to pity him except Neptune, who still persecuted
                him without ceasing and would not let him get home.
              </p>
            </div>
          </div>
        );
    }
    export default App_B;

I get ` Cannot read property 'childNodes' of null`

![image](https://user-images.githubusercontent.com/70313067/114836959-7ade9580-9dd3-11eb-8472-beef269b75d6.png)

**Comment by rsimon** [comment]
It's not that easy. 

- First: are you mounting the text element into a DIV with ID `my-content`?
- Second: you are initializing Recogito even before you call the function, which means that your `my-content` is empty (if it exists). RecogitoJS needs the text to be there, in order to attach annotation functionality.
- Third: do keep in mind that React uses a virtual DOM. You need to wait until the actual DOM nodes were inserted, before you can init RecogitoJS. E.g. you need to do initialization in the `useEffect()` hook.

**Comment by raphael10-collab** [comment]
After chaning the div's ID to `my-content` and using `React.useEffect`

      React.useEffect(() => {
        const r = new Recogito({ content: 'my-content' });
        return () => {// clean-up function: ?

        }
      },[]);


I get no errors

What do you suggest me to pust as `clean-up function` within `React.useEffect()`?

**Comment by rsimon** [comment]
There's currently no sensible operation for cleanup. (Future versions are supposed to get an `r.destroy()` method, but it's not implemented yet.)

**Comment by raphael10-collab** [comment]
Ok.
Waiting then for the future release, I thank you very much for your kind help, an I close the issue.
