### ISSUE TITLE
Add .destroy() method

### ISSUE THREAD

**Issue by rsimon** [recogito/recogito-js#26]

**Comment by kl4n4** [comment]
I am really looking forward for this functionality. Will it be released within the next few days or will it be waiting for other features/PRs?

**Comment by rsimon** [comment]
It's implemented and available now - if you're willing to build from source (or link to a local copy of this repo instead of the last release published on npm) ;-)

I'm almost 100% sure I'll roll another release still in September, though. (I need the destroy() feature for a current paid project with a deadline end Sept. But there may be need for a few more tweaks to RecogitoJS before that, and those will go into the next release, too.)

**Comment by kl4n4** [comment]
ok, thanks for the heads up and the implementation! :)

**Comment by rsimon** [comment]
Thanks - and greetings to Linz (my birthplace), if I saw that correcly ;-)

**Comment by kl4n4** [comment]
yeah, that's right - greetings back to Vienna (just saw that you guys are located in Austria as well) 😉

On another note, are you interested in TypeScript typings for the library? Because we are using your library in an Angular/TypeScript project and currently have simplified custom typings but if there is interest I could prepare and create a PR with complete typings.

**Comment by rsimon** [comment]
Just a quick update: the new release is out:
https://github.com/recogito/recogito-js/releases/tag/v1.4.2
https://www.npmjs.com/package/@recogito/recogito-js

**Comment by kl4n4** [comment]
Thank you very much for that quick release! 👍

It would be just one extra file (index.d.ts) containing type information (and JSdocs for even better IDE support) and would look something like this:
```typescript
declare module '@recogito/recogito-js' {
  interface RecogitoOptions {
    /**
     * REQUIRED the DOM element to make annotate-able or, alternatively, the ID of the element
     */
    content: string | HTMLDivElement;

    /**
     * Set to true to display annotations read-only
     */
    readOnly?: boolean;

    /**
     * For adding custom CSS classes to anntotations (see Formatters)
     */
    formatter?: (annotation: Annotation) => string;

    /**
     * Set the two-character language code for UI localization. Alternatively, use auto to select the language based on the browser setting. See here for a list of currently supported languages.
     */
    locale?: string;

    /**
     * Set this to pre if the content is preformatted text (<pre> tag or white-space: pre CSS style). In pre mode, TextPositionSelectors stored in the annotations will precisely match the text formatting in the markup, whereas positions in html mode will correspond more closely to the character offsets rendered in the browser.
     */
    mode?: 'html' | 'pre';
  }

  class Recogito {
    constructor(options?: RecogitoOptions);

    /**
     * Adds an annotation programmatically. The annotation format is that of the W3C WebAnnotation model. RecogitoJS requires a TextPositionSelector in the annotation, and will display each TextualBody as a field the popup.
     */
    addAnnotation(annotation: Annotation): void;

    /**
     * Removes an annotation programmatically.
     */
    removeAnnotation(annotation: Annotation): void;

    /**
     * Loads annotations from a JSON-LD source. The method returns a promise, in case you want to do something after the annotations have loaded.
     */
    loadAnnotations(url: string): Promise<Annotation[]>;
    
    // ...
  }
  
  // ...
}
```

I will create a PR as soon as I find some time to properly define all types and then you can decide whether you want to include this or not.

**Comment by rsimon** [comment]
That sounds excellent - I'll definitely include that. Many thanks in advance!
