### ISSUE TITLE
Two more questions

### ISSUE THREAD

**Issue by raphael10-collab** [recogito/recogito-js#27]
Hi!
I'm here for a further two-folds request of help.

`1° Question)` In this React tsx page of my Electron-React-Webpack-Typescript app I've put the new instance of Recogito within `React.useEffect`.

  To change the `Recognition Mode` between `ANNOTATION` and `RELATIONS`, I set a ToggleSwitch for which I attached an `onAnnotationModeChange` function. For making this function being able to change the Recognition Mode with `r.setMode` I had to put this function within `React.useEffect`. 

But in this way  I get this error : 

    Cannot find name 'onAnnotationModeChange'.

    155           onChange={onAnnotationModeChange}
                            ~~~~~~~~~~~~~~~~~~~~~~

This is the React page: 


    function App_B() {

      React.useEffect(() => {
        let r = new Recogito({ content: 'my-content' });

        r.on('createAnnotation', function(a) {
          console.log('created', a);
        });

        r.on('updateAnnotation', function(annotation, previous) {
          console.log('updated', previous, 'with', annotation);
        });

        r.on('removeAnnotation', function(a) {
          r.removeAnnotation(a);
        });

        const onAnnotationModeChange = (checked) => {
          setAnnotationMode(checked);
          if (!checked) {
            r.setMode('RELATIONS');
          }
        }

        return () => { // clean-up function

        }
      },[]);


      let [annotationMode, setAnnotationMode] = React.useState(false);

        return (
          <div className='outer-container'>

            <ToggleSwitch
              id="annotationMode"
              checked={annotationMode}
              onChange={onAnnotationModeChange}
            />

            <div id="my-content" className="plaintext">
              <h1>Homer: The Odyssey</h1>
              <p>
                <strong>Tell me, O muse,</strong> of that ingenious hero who travelled far and wide after he had sacked
                the famous town of Troy. Many cities did he visit, and many were the nations with whose manners and customs
                he was acquainted; moreover he suffered much by sea while trying to save his own life and bring his men safely
                home; but do what he might he could not save his men, for they perished through their own sheer folly in eating
                the cattle of the Sun-god Hyperion; so the god prevented them from ever reaching home. Tell me, too, about all
                these things, O daughter of Jove, from whatsoever source you may know them.
              </p>
              <p>
                <strong>So now all who escaped death in battle</strong> or by shipwreck had got safely home except Ulysses,
                and he, though he was longing to return to his wife and country, was detained by the goddess Calypso, who
                had got him into a large cave and wanted to marry him. But as years went by, there came a time when the gods
                settled that he should go back to Ithaca; even then, however, when he was among his own people, his troubles
                were not yet over; nevertheless all the gods had now begun to pity him except Neptune, who still persecuted
                him without ceasing and would not let him get home.
              </p>
            </div>


      </div>
    );
}

export default App_B;


If I put the the function `onAnnotaionModeChange` outside of React.useEffect:


      let r;

      React.useEffect(() => {

        //let r = new Recogito({ content: 'my-content' });
        r = new Recogito({ content: 'my-content' });

       r.on('createAnnotation', function(a) {
          console.log('created', a);
        });

        r.on('updateAnnotation', function(annotation, previous) {
          console.log('updated', previous, 'with', annotation);
        });

        r.on('removeAnnotation', function(a) {
          r.removeAnnotation(a);
        });

    return () => { // clean-up function
    }
  },[]);

    const onAnnotationModeChange = (checked) => {
      setAnnotationMode(checked);
      if (!checked) {
        r.setMode('RELATIONS');
      }

The previous error disappears, but the change of mode doesn't work.



`2° Question)`

![image](https://user-images.githubusercontent.com/70313067/114987601-a32ec880-9e95-11eb-8391-bb9e7f5c219e.png)

![image](https://user-images.githubusercontent.com/70313067/114987848-ea1cbe00-9e95-11eb-828f-fb57d95aeb3c.png)

![image](https://user-images.githubusercontent.com/70313067/114987959-12a4b800-9e96-11eb-85a1-9b7b61682b30.png)

When an annotation is created, the `annotation` object has an `id` element. 

My objective is to store the annotations in a sqlite local db and, in case the annotation is being deleted / modified from the UI, delete /modify the corresponding store annotation in the local db. 
It's not clear to me how to retrieve the `id` element of the annotation upon which we make an action: deletion or modification ( https://github.com/recogito/recogito-js/wiki/API-Reference#removeannotationannotation )

**Comment by rsimon** [comment]
Yes, wrapping non-React libraries in React can be a bit tricky. I'll try to dig a bit deeper, if I have the time later, but:

- Yes, the `onAnnotationModeChange` function must be outside of the effect handler, otherwise, it is simply not visible.
- Likewise, `r` is scoped to the effect handler function, it needs to be declared outside of the handler, otherwise it's simply not visible.

Therefore, your steps look right in principle. To debug: can you log wether the `onAnnotationModeChange` actually being called? And if it is, can you check whether `r` is a valid RecogitoJS instance?

Concerning your second question: I'm not sure I understand that correctly. The ID is in the annotation object as `annotation.id`. When storing in SQLite, you can e.g. use this ID as the ID of the database record. If you prefer to use your own SQLite-generated IDs, you can also [override the ID](https://github.com/recogito/recogito-js/wiki/API-Reference#createannotationannotation-overrideid) after the record was created in the DB. When the user deletes or modifies the annotation in the UI, you need to replicate those deletes/updates in SQLite. Is this what you mean?

**Comment by raphael10-collab** [comment]
Regarding my second question: yes I need to replicate my deletes/updates in SQLite

First question: I do not see any change of mode: what am I missing?

    React.useEffect(() => {
      r = new Recogito({ content: 'my-content' });

      r.on('createAnnotation', function(a) {
        console.log('created', a);
      });

      r.on('updateAnnotation', function(annotation, previous) {
        console.log('updated', previous, 'with', annotation);
      });
    
      r.setMode(toggleMode);

      return () => { // clean-up function
        //     
      }
    },[]);


      const [toggleMode, setToggleMode] = React.useState('ANNOTATION')

      const toggleFunct = React.useCallback(() => {
        setToggleMode(s => (s === 'ANNOTATION' ? 'RELATIONS' : 'ANNOTATION'));
      }, []);


        return (
          <div className='outer-container'>

            <div id="my-content" className="plaintext">
              <h1>Homer: The Odyssey</h1>
              <p>
                <strong>Tell me, O muse,</strong> of that ingenious hero who travelled far and wide after he had sacked
                the famous town of Troy. Many cities did he visit, and many were the nations with whose manners and customs
                he was acquainted; moreover he suffered much by sea while trying to save his own life and bring his men saf$
                home; but do what he might he could not save his men, for they perished through their own sheer folly in ea$
                the cattle of the Sun-god Hyperion; so the god prevented them from ever reaching home. Tell me, too, about $
                these things, O daughter of Jove, from whatsoever source you may know them.
              </p>
              <p>
                <strong>So now all who escaped death in battle</strong> or by shipwreck had got safely home except Ulysses,
                and he, though he was longing to return to his wife and country, was detained by the goddess Calypso, who
                had got him into a large cave and wanted to marry him. But as years went by, there came a time when the gods
                settled that he should go back to Ithaca; even then, however, when he was among his own people, his troubles
                were not yet over; nevertheless all the gods had now begun to pity him except Neptune, who still persecuted
                him without ceasing and would not let him get home.
              </p>
            </div>
            <hr />
            <div>
              <div>State: {toggleMode}</div>
              <button type="button" onClick={toggleFunct}>Toggle Mode</button>
            </div>
          </div>
        );

![image](https://user-images.githubusercontent.com/70313067/115055312-959f3000-9ee1-11eb-9fac-01a8e56e254a.png)

**Comment by rsimon** [comment]
This cannot work. You are calling setMode only when your component first renders. But then never again. (You are only changing the value of the state variable. But that doesn't affect Recogito.) You need to call setMode when the button is toggled.

**Comment by raphael10-collab** [comment]
I actually forgot to call r.setMode when the button is toggled.
But even with that, it doesn't work : 


    const toggleFunct = React.useCallback(() => {
        setToggleMode(s => (s === 'ANNOTATION' ? 'RELATIONS' : 'ANNOTATION'));
        r.setMode(toggleMode);
      }, []);

So... I still miss something

**Comment by rsimon** [comment]
Sorry, you'll need to debug this. It's not an issue specific to Recogito, but a general problem when wrapping vanilla JS in React. 

I my guess is your component re-renders, probably on every state change, whereas you are only initializing once, when your component renders first. When it renders next (after the state change) r is null, because it's being redefined at the start of your component, but never initialized.

You'll definitely need to separate your wrapper around RecogitoJS, and your own button state logic. Otherwise this can't work.

But as I said: it's really a matter of debugging the process of initialization and component re-renders.

**Comment by raphael10-collab** [comment]
I'm actually debugging now... Thanks for your kind help.
I close the issue

**Comment by rsimon** [comment]
Ok, thx. I'm pretty sure the root issue is that your code keeps re-rendering the text (thus destroying RecogitoJS), whereas RecogitoJS init happens only once on initial render.

You'll definitely need to split into several components, one that only has the text + RecogitoJS, but then never re-renders. Others that handle the rest of your UI. I don't say off the top of my head what full solution would look like. A proper React wrapper is definitely on the wishlist, but nothing I'll be able to do anytime soon.

If you manage to find a good solution, do let me know!

**Comment by raphael10-collab** [comment]
@rsimon 

It seems that with this simple code the `RELATIONSHIP` mode now works: 

      const [toggleMode, setToggleMode] = React.useState('ANNOTATION');

      React.useEffect(() => {
        const recogitoFunct = () => {
          r = new Recogito({ content: 'my-content' });

          r.on('createAnnotation', function(a) {
            console.log('created', a);
          });

          r.on('updateAnnotation', function(annotation, previous) {
            console.log('updated', previous, 'with', annotation);
          });
          r.setMode(toggleMode);
        }
        recogitoFunct();


        return () => { // clean-up function

        }
      },[toggleMode]);


![image](https://user-images.githubusercontent.com/70313067/115109673-76eb7880-9f77-11eb-9575-bbbdd89b5dee.png)

**Comment by rsimon** [comment]
Good catch - yes, indeed this will make it work. Keep in mind though that this completely re-initializes Recogito when you toggle the switch (and then sets the mode to `toggleMode`. It might start to get slow (or create a memory leak) eventually. If you manage to split up your components, so that only Text + Recogito is in one component, then this will probably end up being a more robust solution. (But, in principle: as long as it works, it works ;-)

**Comment by rsimon** [comment]
For info: I made a Gist for using Annotorious with React. The basic idea will work for RecogitoJS, too. Maybe it's helpful:
https://gist.github.com/rsimon/2391fdf2c49bdeef5125407306c2db93
