### ISSUE TITLE
How to save?

### ISSUE THREAD

**Issue by KoljaL** [recogito/recogito-js#3]
Hey

great Idea to offer the possibility to make comments on websites like in PDFs!

I tried this demo: https://github.com/recogito/recogito-js/tree/gh-pages,
but my annotiations will not be saved in the .json file.

What is my mistake?

**Comment by rsimon** [comment]
Server-side storage is beyond the scope of this library. RecogitoJS is an embeddable software component that runs in the browser. If you build a website that should have annotation functionality, you'll usually have some sort of backend in place already. RecogitoJS provides a JavaScript API that you can use to connect your backend yourself (depending on the type of technology you are using). 

The API is documented [on the Wiki](https://github.com/recogito/recogito-js/wiki/Developer-Documentation). You should specifically look at the events:

https://github.com/recogito/recogito-js/wiki/Developer-Documentation#events

If you are looking for a full-stack solution for annotating documents, you may want to check out the [Recogito platform](http://recogito.pelagios.org). An "annotation-as-a-service" solution, like you are expecting (which also takes care of storing annotations for you) may come in the future perhaps. But either way, this would be a separate project.

**Comment by KoljaL** [comment]
Thanks for your quick reply with the detailed explanation. Unfortunately I have to wait until someone else implements this function, because I am not familiar with javascript. An external service is out of the question for me, but I saved the link anyway.

**Comment by rsimon** [comment]
Saving annotations permanently will always require some kind of online storage or database, whether you run your own Web application, or rely on a cloud service. FWIW: I just published an example for how you can, fairly easily use [Google Firebase](https://firebase.google.com/) as a personal annotation server:

https://github.com/recogito/annotorious/wiki/Using-Firebase-for-Storage

(The example is for [Annotorious](https://github.com/recogito/annotorious), the image annotation
counterpart to RecogitoJS. But the example is applicable in exactly the same way.)
