### ISSUE TITLE
Docs for relations mode?

### ISSUE THREAD

**Issue by gabrielbuzziv** [recogito/recogito-js#32]
Guys, can you please provide a documentation for relation?

**Comment by rsimon** [comment]
One day I'll hopefully find the time to build a proper project website for RecogitoJS... but in the meantime, here's some basic info:

## Relation Data Format

Each relation is stored as an annotation, just like the text highlight annotations. The difference is in the `target`: while the target of a text annotation points to a specific character offset, the target of a relation points to two text annotations. By convention, the first ID in the list is the ID of the starting annotation.

Another difference between text and relation annotations is that relationships have a `motivation` property of `linking`. (For full details of the W3C Web Annotation data model see [the official docs](https://www.w3.org/TR/annotation-model/).

__Example:__

```json
"target": [{
    "id": "#ce0ed291-766b-4763-8e91-90ce1d04e706"
  }, {
    "id": "#447d4bea-08dc-4bd0-ae51-31f5ed7a95a0"
}]
```

__For comparison, the target of a text highlight annotation:__

```json
"target": {
  "selector": [{
    "type": "TextQuoteSelector",
    "exact": "death in battle"
  }, {
    "type": "TextPositionSelector",
    "start": 646,
    "end": 661
  }]
}
```

__Full relation annotation example__, including the relationship tag as an annotation body.

```json
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "#9ba844a7-e8ec-4127-ad12-1f7f16a240c6",
  "type": "Annotation",
  "motivation": "linking",
  "body": [{
    "type": "TextualBody",
    "value": "isRelatedTo",
    "purpose": "tagging"
  }],
  "target": [{
    "id": "#ce0ed291-766b-4763-8e91-90ce1d04e706"
  }, {
    "id": "#447d4bea-08dc-4bd0-ae51-31f5ed7a95a0"
  }]
}
``` 

## Using Autocomplete

The relationship editor can be configured with a pre-set tag vocabulary, using the `relationVocabulary` init property. (__Note that the name of the property might change in future versions!__)

__Example:__

```js
var r = Recogito.init({
  content: document.getElementById('my-content'),
  relationVocabulary: [ 'knows', 'isChildOf', 'isSiblingOf', 'livesAt' ]
});
```

**Comment by rsimon** [comment]
Let me know if this is the information you are looking for, or if you need anything else.

**Comment by gabrielbuzziv** [comment]
Thanks
