### ISSUE TITLE
Ability to work only with TextPositionSelector and without TextQuoteSelector

### ISSUE THREAD

**Issue by reckart** [recogito/recogito-js#34]
I would like to be able to use RecogitoJS without having to send a TextQuoteSelector which would create a lot of unnecessary data between client and server especially for long ranges. If there is a TextPositionSelector, it should be enough. Unfortunately, the current code won't work without a TextQuoteSelector:

<img width="733" alt="Screenshot 2021-06-27 at 16 38 20" src="https://user-images.githubusercontent.com/1410238/123548730-535a6080-d766-11eb-9d0c-4da8312c8ab8.png">

**Comment by rsimon** [comment]
After a brief look, I think the quote is only used in a few places to sort annotations by length. (In order to determine the top-most annotation on click.) This, obviously can be done with TextPosition alone, too.

Would you be up for a pull request on this one?

**Comment by reckart** [comment]
Incoming...

**Comment by reckart** [comment]
I did a PR with a quick fix. A better fix would probably be to move fetching the length entirely into the annotation object and then the annotation can use either the position or the quote to calculate the length - depending on what is available - and the code that sorts by length no longer has to worry about how to calculate the length.

**Comment by rsimon** [comment]
Many thanks! I agree, length would ideally be a property/method of the annotation. But this works well for now :-)
