### ISSUE TITLE
Ability to create relations / select relations without having to switch to "relation" mode

### ISSUE THREAD

**Issue by reckart** [recogito/recogito-js#37]
It would be great if there was a way to select relations and to create relations without having to switch the the "relations" mode before. I.e. the ability to create span annotations and relation annotations without mode-switching.

Optimally, I believe there would be some handle on the spans which can be used to create a relation be clicking on the handle and then dragging it to the target.

An alternative could be to involve a key-press. E.g. when shift-clicking on a span and then dragging the mouse, that this would initiate the creation of a relation.

**Comment by rsimon** [comment]
Definitely +1 on a keyboard shortcut. 

As for an interaction that doesn't require switching modes: I agree this would be much better, and I'm really interested in ideas/designs around this. (Also because I'm about to release a similar plugin for Annotorious, and would also prefer a more streamlined interaction there.)

**Comment by rsimon** [comment]
__Update:__ we're in the process of re-designing relationship mode. In terms of codebase organization, relationship mode will be removed from RecogitoJS as a feature, and instead become a separate plugin. Work happens in this repository:

https://github.com/recogito/recogito-connections

I created a first discussion/requirements-gathering ticket here, for anyone who wants to chip in:
https://github.com/recogito/recogito-connections/issues/1

**Comment by rsimon** [comment]
P.S.: I'm closing this issue in favour of the new repo + discussion ticket.
