### ISSUE TITLE
Possibility to add headers for .loadAnnotations?

### ISSUE THREAD

**Issue by Apeli** [recogito/recogito-js#45]
We use JWT auth for our apps authentication, and all requests must have a Authorization header. 

Would this be ok?

`loadAnnotations = (url, headers) => fetch(url, headers)
    .then(response => response.json()).then(annotations => {
      this.setAnnotations(annotations);
      return annotations;
    });`

**Comment by rsimon** [comment]
+1 this sounds good & I'm happy to take a PR die this. Although, technically, I think the second argument to `fetch` is a requestArgs object (which can include custom headers) rather than just the headers. So perhaps the arg should be renamed accordingly?

**Comment by rsimon** [comment]
Closed with PR #46
