### ISSUE TITLE
Timeline for new release?

### ISSUE THREAD

**Issue by Apeli** [recogito/recogito-js#47]
Can you estimate when a new versions of the libraries will be published to the npm registry?

**Comment by rsimon** [comment]
Can't say exactly. But I do have an ongoing client project with AnnotoriousOSD, and (hopefully) a client project upcoming with RecogitoJS. Therefore, I expect to publish fairly soon-ish (mid- to end September).

**Comment by rsimon** [comment]
The [new release](https://github.com/recogito/recogito-js/releases/tag/v1.4.1) is out! 🎉
