### ISSUE TITLE
Custom component

### ISSUE THREAD

**Issue by marcomoretto** [recogito/recogito-js#48]
Is there the possibility to use custom component (such as a combo-box) instead of text area when adding a new annotation?
Thanks!

**Comment by rsimon** [comment]
Yes :-) Documentation for custom widgets is a bit underdeveloped, but the API as such is there, and pretty comprehensive.

See here for guides to get you started:
https://recogito.github.io/guides/configuring-the-editor/
https://recogito.github.io/guides/editor-widgets/
https://recogito.github.io/guides/example-react-widget/

The guides are focused on [Annotorious](https://annotorious.com), RecogitoJS's "sister project" for image annotation. But the editor component is shared, and editor plugins are compatible with both systems.
