### ISSUE TITLE
RelationEditor: onClick and PointerEvent

### ISSUE THREAD

**Issue by MicheleMallia** [recogito/recogito-js#56]
Hi everyone,
 
I have a problem when I create a relation between the annotation when I click on the svg icon to confirm the tag name of relation. Instead of passing correct string values the component get the PointerEvent value (corresponding to the click of the mouse and not the text value inserted before).

Is there any method to pass the string instead of the PointerEvent?

Thanks.

p.s: I know that relations will be unsupported by this library but I need this component for a personal project.

**Comment by rsimon** [comment]
Hi,

I'm not sure I understand correctly. Are you using the React component directly? Can you post your code?

**Comment by MicheleMallia** [comment]
I've cloned this repo and I've tested the component.

Steps:

1) Open Index.html
2) Create a new annotation
3) Switch to Relation Mode
4) Linking two annotations
5) Insert Tag
6) Click in the 'ok' icon svg
7) Get this error:

![Schermata da 2021-12-19 22-01-51](https://user-images.githubusercontent.com/32638550/146690643-29b7fcc3-77ad-4b19-8408-07d9e02cae51.png)


This is the video steps action:

![Screencast da 20-12-2021 00_27_20](https://user-images.githubusercontent.com/32638550/146694894-26e42b5a-ea99-4858-8e62-d84e630ad31f.gif)


This happens because the value of onSubmit methods is a PointerEvent (svg element is outside the Autocomplete component, so it pass the mouse click, instead if I press enter key when I type inside the autocomplete input, it works).

Is this normal, or I've done some error? Sorry for my bad english.

**Comment by rsimon** [comment]
Ah - thanks for the extra info. Looks like this is a regression bug caused by a recent change. Will look into it!

**Comment by rsimon** [comment]
Thanks again for reporting this. The bug is fixed now & everything will work again with the next release (v1.6.2).

**Comment by MicheleMallia** [comment]
No problem, I'm happy to notify bugs! :D
