### ISSUE TITLE
The editor does not allow selection of text in readonly mode

### ISSUE THREAD

**Issue by systoyanov** [recogito/recogito-js#60]
When trying to select text inside the content element(with "readOnly" enabled) the selected text gets deselected upon right mouse click so it's impossible for the user to copy it via the context menu.
In my POV the problem comes from the clearSelection method in SelectionHandler class which could be evolved to respect the read only mode. 

I patched it locally with a simple 
`if(this.readOnly) {
    return;
}`
in the beginning of the method. 

This suits my needs but as I'm not familiar with all the features it is possible that it's a very usecase realated fix and will break some other usecases I don't use.

**Comment by rsimon** [comment]
Ah - thanks for spotting! Your solutions looks pretty good + clean. I'll just double check if there are any unwanted side effects to it, and make this change it if not.

Thx,
R

**Comment by rsimon** [comment]
This should work now. I made a small change: `clearSelection` is now prevented specifically for right click (regardless of whether in readOnly mode or not). But seems to have pretty much the same effect. The fix will be available with the next release (probably out soon).

**Comment by systoyanov** [comment]
@rsimon Thanks for your reactivity and all the work you have done on this library.
It's great:)
