### ISSUE TITLE
Unable to annotate in Windows 10 IE11

### ISSUE THREAD

**Issue by dennisgaebel** [recogito/recogito-js#7]
console report

![Screenshot 2020-06-10 15 46 36](https://user-images.githubusercontent.com/13485205/84311640-a51b5300-ab31-11ea-9a69-07f7222626a6.png)

**Comment by rsimon** [comment]
Looks like the problem is `Array.from`. See https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/from

**Comment by rsimon** [comment]
The latest release [1.0.8](https://github.com/recogito/recogito-js/releases/tag/v1.0.8) should address most IE11 related issues.
