### ISSUE TITLE
Two annotations on the exact same piece of text

### ISSUE THREAD

**Issue by kdaniel21** [recogito/recogito-js#76]
Hi!

While we were testing the library, we've found another bug with @st3h3n. It's rather weird as it doesn't appear on all parts of the text, still, where it appears, it is consistently reproduceable. Normally, when annotating a piece of text, and then trying to annotate it again, the already existing annotation opens up. Yet, in some cases, a new annotation is created, making the original annotation "unreachable".

![Peek 2022-07-14 17-41](https://user-images.githubusercontent.com/39854385/179022374-e24f65f2-1026-475e-9674-7897218aeddd.gif)

**Comment by rsimon** [comment]
Weird - I couldn't reproduce this, even on the exact same piece of text. I tried selecting the exact same passage, same passage + space before, passage + space after, and with spaces before and after. It always opened the existing annotation. Which version of RecogitoJS are you using in this screen recording?

**Comment by kdaniel21** [comment]
@rsimon This is the publicly available demo, so provided that you're showcasing the latest version, it is the latest version. Could you create a GIF of you reproducing it? It might help us identify what the difference is.
As far as I'm aware, it shouldn't only exist on my end since two other people could also reproduce it.

**Comment by rsimon** [comment]
See here: https://github.com/recogito/recogito-js/issues/75#issuecomment-1195553590

The online demo is running an outdated build. Sorry for this!

**Comment by kdaniel21** [comment]
Excuse me for the late response. Using the newest version in a different environment, I haven't managed to reproduce the error, so there's a high chance that it has been fixed indeed. I'm closing the issue for now, and I'll reopen it if we run into it ever again. Thank you for you quick help!
